### PR TITLE
Add new feature of bigquery-avro-load job

### PR DESCRIPTION
**Pull request by seii-saintway**
Work together with [fluent-plugin-avro](https://github.com/takebayashi/fluent-plugin-avro)
### Acknowledgements
I would like to extend my sincere gratitude to my team leader, for his instructive advice and useful discussions make me realize where the problem is.

### CODE REVIEW

**Comment by seii-saintway** [comment]
There’re API errors of EOF, because of the synchronization of the variable @avro_writer.block_count. And I feel difficult to solve this problem, so maybe it’s better to solve the avro-format problem in the fluent-plugin-avro.

**Comment by seii-saintway** [comment]
=> Use chunk.size to reset @avro_writer.block_count

**Comment by seii-saintway** [comment]
I'd found a mistaken in README.md :
chunk_records_limit → chunk_limit_records

**Comment by joker1007** [comment]
I'm sorry.
This method does not seem to have any performance advantages.
It would be better to generate avro with a formatter plugin.

**Pull request closed without merging**
