### PR TITLE
Add require_partition_filter support

### PR DESCRIPTION
**Pull request by hirose31**
Support [requirePartitionFilter](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables?#resource:-table) option.

### CODE REVIEW

**Comment by hirose31** [comment]
@joker1007 Please let me know if you need more information concerning this PR.

**Comment by joker1007** [comment]
This patch doesn't seem to enable to support `requirePartitionFilter`.
According to the official API reference, the configuration of a load job doesn't accept `requirePartitionFilter` option.
(cf. https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#jobconfigurationload)

If this plugin supports `requirePartitionFilter` option, you probably have to separate the table creation and load job creation that is not a simple task.
And, I'm sorry. I don't have enough time for such a task.

**Comment by hirose31** [comment]
The `tables.insert` API supports `requirePartitionFilter`, so what about implementations that add options only to `bigquery_insert`?
https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#Table

**Comment by joker1007** [comment]
> The tables.insert API supports requirePartitionFilter, so what about implementations that add options only to bigquery_insert?

Do you mean that you add `requirePartitionFilter` support only to `insert` mode?
It's not a bad option. I welcome the plan.

**Comment by hirose31** [comment]
Support `require_partition_filter` option for only `bigquery_insert`.

If any advise, I will revise code.

**Comment by hirose31** [comment]
> I think it is better to pass require_partition_filter option to the constructor of Fluent::BigQuery::Writer and to use @options[:require_partition_filter] instead of adding new argument.

done! https://github.com/fluent-plugins-nursery/fluent-plugin-bigquery/pull/189/commits/010fa1f5ff0d82fc17ca53f4640306f7a6f7c9f9

**Review by joker1007 — APPROVED** [review]
LGTM!
Many thanks!

**Pull request merged**
